/**
 * This class represents a node in your BST.
 * DO NOT EDIT THIS FILE.
 *
 * @version 1.0
 * @author CS 1332 TAs
 */
public class BSTNode {
    private int data;
    private BSTNode left;
    private BSTNode right;

    /**
     * Create a BST node with the given data.
     *
     * @param data the data to be stored in this node.
     */
    public BSTNode(int data) {
        this.data = data;
    }

    /**
     * Get the data in this node.
     *
     * @return data in this node.
     */
    public int getData() {
        return data;
    }

    /**
     * Set the data in this node.
     *
     * @param data data to be placed into the node.
     */
    public void setData(int data) {
        this.data = data;
    }

    /**
     * Get the node to the left of this node.
     *
     * @return node to the left.
     */
    public BSTNode getLeft() {
        return left;
    }

    /**
     * Set the node to the left of this node.
     *
     * @param left new node to the left.
     */
    public void setLeft(BSTNode left) {
        this.left = left;
    }

    /**
     * Get the node to the right of this node.
     *
     * @return node to the right.
     */
    public BSTNode getRight() {
        return right;
    }

    /**
     * Set the node to the right of this node.
     *
     * @param right new node to the right.
     */
    public void setRight(BSTNode right) {
        this.right = right;
    }
}
